openapi: 3.0.0
servers:
  - url: https://app-auth-staging.bananasign.co/api/web/v1
    description: Resource server
info:
  description: |
    Bananasign resource server
  title: Bananasign resource server specification
  version: 1.0.0
tags:
  - name: Create contract temporary
    description: Create contract temporary flow
components:
  schemas:
    Init:
      $ref: 'components/Init.yml#/components/schemas/Init'
      xml:
        name: Init
    InitPayload:
      $ref: 'components/Init.yml#/components/schemas/InitPayload'
      xml:
        name: InitPayload
    ContractTemporary:
      $ref: 'components/ContractTemporary.yml#/components/schemas/ContractTemporary'
      xml:
        name: ContractTemporary
    ContractTemporaryPayload:
      $ref: 'components/ContractTemporary.yml#/components/schemas/ContractTemporaryPayload'
      xml:
        name: ContractTemporaryPayload